const { chromium } = require('playwright');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs/promises');
const assert = require('node:assert/strict');

(async () => {
  const dir = path.resolve(__dirname, '..', '.artifacts'); await fs.mkdir(dir, { recursive: true });
  const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  page.on('dialog', d => d.accept());
  await page.goto(pathToFileURL(path.resolve(__dirname, '../index.html')).href);
  await page.waitForFunction(() => document.querySelector('#output-size').textContent.includes('px'));
  await page.locator('#use-demo').click(); await page.locator('#detect').click();
  await page.waitForFunction(() => document.body.dataset.step === '3');
  await page.locator('[data-step="4"]').click();
  console.log('Initial:', await page.locator('#output-size').textContent(), await page.locator('#grid-status').textContent());
  const nonblank = await page.locator('#source-canvas').evaluate(c => { const d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data; return new Set(Array.from({ length: d.length / 400 }, (_, i) => Array.from(d.slice(i * 400, i * 400 + 3)).join(','))).size; });
  assert.ok(nonblank > 20);
  assert.equal(await page.locator('#cols').inputValue(), '48');
  assert.equal(await page.locator('#rows').inputValue(), '48');
  assert.ok(await page.evaluate(() => document.querySelector('.canvas-footer').getBoundingClientRect().bottom <= innerHeight + 1));
  await page.screenshot({ path: path.join(dir, 'desktop.png'), fullPage: true });
  const canvas = page.locator('#source-canvas'); let box = await canvas.boundingBox();
  await page.mouse.click(box.x + box.width * 0.505, box.y + box.height * 0.695);
  assert.equal(await page.locator('#selection-badge').textContent(), '1 格');
  const initialX = Number(await page.locator('#sample-x').inputValue());
  await page.getByRole('button', { name: '向右移动取样', exact: true }).click();
  assert.equal(Number(await page.locator('#sample-x').inputValue()), initialX + 1);
  assert.equal(await page.locator('#local-count').textContent(), '1 格');
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  assert.equal(await page.locator('#local-count').textContent(), '0 格');
  await page.getByRole('button', { name: '重做', exact: true }).click();
  assert.equal(await page.locator('#local-count').textContent(), '1 格');
  await page.mouse.click(box.x + box.width * 0.505, box.y + box.height * 0.695);
  await page.locator('#cell-color').fill('#ff00ff'); await page.locator('#apply-color').click();
  assert.equal(await page.locator('#manual-count').textContent(), '1 格');
  await page.locator('#export-scale').selectOption('1');
  const pngPromise = page.waitForEvent('download'); await page.locator('#export').click(); const png = await pngPromise; const pngPath = path.join(dir, 'export.png'); await png.saveAs(pngPath);
  const pngBytes = await fs.readFile(pngPath); assert.equal(pngBytes.readUInt32BE(16), 48); assert.equal(pngBytes.readUInt32BE(20), 48);
  const projectPromise = page.waitForEvent('download'); await page.locator('#save-project').click(); const projectDownload = await projectPromise; const projectPath = path.join(dir, 'project.json'); await projectDownload.saveAs(projectPath);
  const project = JSON.parse(await fs.readFile(projectPath, 'utf8')); assert.equal(Object.keys(project.colors).length, 1); assert.equal(Object.keys(project.samples).length, 1);
  assert.ok(Object.values(project.colors).some(c => c.join(',') === '255,0,255,255'));
  await page.locator('#project-input').setInputFiles(projectPath);
  await page.waitForFunction(() => document.querySelector('#toast').textContent === '项目已打开');
  await page.locator('[data-step="4"]').click();
  assert.equal(await page.locator('#manual-count').textContent(), '1 格');
  await page.mouse.click(box.x + box.width * 0.505, box.y + box.height * 0.695);
  await page.getByRole('button', { name: '矩形取样', exact: true }).click();
  await page.mouse.move(box.x + box.width * 0.3, box.y + box.height * 0.3); await page.mouse.down(); await page.mouse.move(box.x + box.width * 0.34, box.y + box.height * 0.36, { steps: 8 }); await page.mouse.up();
  assert.ok(Number(await page.locator('#sample-w').inputValue()) > 15);
  await page.getByRole('button', { name: '选择格子', exact: true }).click();
  await page.mouse.move(box.x + box.width * 0.41, box.y + box.height * 0.41); await page.mouse.down(); await page.mouse.move(box.x + box.width * 0.48, box.y + box.height * 0.48, { steps: 6 }); await page.mouse.up();
  assert.ok(parseInt(await page.locator('#selection-badge').textContent()) > 1);
  await page.getByRole('button', { name: '移动取样区域', exact: true }).click();
  await page.mouse.move(box.x + box.width * 0.43, box.y + box.height * 0.43); await page.mouse.down(); await page.mouse.move(box.x + box.width * 0.45, box.y + box.height * 0.45, { steps: 5 }); await page.mouse.up();
  assert.ok(parseInt(await page.locator('#local-count').textContent()) > 1);
  await page.locator('[data-step="3"]').click();
  await page.getByRole('button', { name: '调整网格线', exact: true }).click();
  await page.mouse.move(box.x + box.width * 0.5, box.y + box.height * 0.22); await page.mouse.down(); await page.mouse.move(box.x + box.width * 0.504, box.y + box.height * 0.22, { steps: 4 }); await page.mouse.up();
  assert.equal(await page.locator('#grid-status').textContent(), '手动网格');
  await page.screenshot({ path: path.join(dir, 'edited.png'), fullPage: true });
  // Import a generated transparent image to verify both decoding and alpha export.
  const fixture = await page.evaluate(() => { const c = document.createElement('canvas'); c.width = 80; c.height = 60; const ctx = c.getContext('2d'); ctx.fillStyle = '#126ac8'; ctx.fillRect(20, 20, 20, 20); return c.toDataURL(); });
  const fixturePath = path.join(dir, 'transparent.png'); await fs.writeFile(fixturePath, Buffer.from(fixture.split(',')[1], 'base64'));
  await page.locator('#image-input').setInputFiles(fixturePath);
  await page.locator('#crop-dialog[open]').waitFor(); await page.locator('#crop-skip').click();
  await page.locator('#confirm-dialog[open]').waitFor(); await page.locator('#confirm-dialog button[value=confirm]').click();
  await page.waitForFunction(() => document.querySelector('#filename').textContent === 'transparent.png');
  assert.equal(await page.locator('#manual-count').textContent(), '0 格');
  const alpha = await page.locator('#preview-canvas').evaluate(c => c.getContext('2d').getImageData(0, 0, 1, 1).data[3]); assert.equal(alpha, 0);
  const aspect = await page.locator('#preview-canvas').evaluate(c => { const r = c.getBoundingClientRect(); return Math.abs(r.width / r.height - c.width / c.height); }); assert.ok(aspect < 0.01);
  // Fresh document keeps mobile verification independent of unsaved state.
  await page.goto(pathToFileURL(path.resolve(__dirname, '../index.html')).href);
  await page.waitForFunction(() => document.querySelector('#output-size').textContent.includes('px'));
  const tuningFixture = await page.evaluate(() => {
    const c = document.createElement('canvas'); c.width = 240; c.height = 120;
    const context = c.getContext('2d'), xs = [0, 20, 40, 60, 64, 80, 120, 140, 160, 180, 200, 220, 240];
    for (let row = 0; row < 6; row++) for (let col = 0; col < xs.length - 1; col++) {
      context.fillStyle = `rgb(${col % 2 ? 230 : 20},${row % 2 ? 230 : 20},50)`;
      context.fillRect(xs[col], row * 20, xs[col + 1] - xs[col], 20);
    }
    return { version: 1, name: '局部网格测试', image: c.toDataURL(), width: 240, height: 120, xs, ys: [0, 20, 40, 80, 100, 120], samples: {}, colors: {}, threshold: 16, edgeWeight: 0.35 };
  });
  const tuningPath = path.join(dir, 'tuning-fixture.json'); await fs.writeFile(tuningPath, JSON.stringify(tuningFixture));
  await page.locator('#project-input').setInputFiles(tuningPath);
  await page.waitForFunction(() => document.querySelector('#filename').textContent === '局部网格测试');
  assert.equal(await page.locator('#grid-issue-count').textContent(), '2 处过宽 · 1 处过窄');
  for (const expected of ['列 4：', '列 6：', '行 3：']) {
    await page.locator('#next-grid-issue').click();
    assert.ok((await page.locator('#toast').textContent()).includes(expected));
    assert.equal(await page.locator('#selection-badge').textContent(), '1 格');
  }
  await page.locator('[data-step="2"]').click();
  await page.locator('#spacing-candidates button').first().click();
  assert.ok(Number(await page.locator('#hint-x').inputValue()) > 0);
  for (const [id, value] of Object.entries({ 'search-ratio': '0.4', 'local-window': '128', 'narrow-ratio': '0.7', 'wide-ratio': '1.8', 'hint-x': '20', 'hint-y': '20' })) {
    await page.locator('#' + id).fill(value); await page.locator('#' + id).press('Tab');
  }
  const tunedDownload = page.waitForEvent('download'); await page.locator('#save-project').click();
  const tunedPath = path.join(dir, 'tuned-project.json'); await (await tunedDownload).saveAs(tunedPath);
  const tuned = JSON.parse(await fs.readFile(tunedPath, 'utf8'));
  assert.deepEqual(tuned.gridOptions, { searchRatio: 0.4, narrowRatio: 0.7, wideRatio: 1.8, localWindow: 128, aggressive: true, hintX: 20, hintY: 20 });
  await page.locator('#project-input').setInputFiles(tunedPath);
  await page.waitForFunction(() => document.querySelector('#toast').textContent === '项目已打开');
  assert.equal(await page.locator('#local-window').inputValue(), '128');
  await page.locator('[data-step="2"]').click();
  await page.locator('#detect').click();
  await page.locator('#confirm-dialog[open]').waitFor(); await page.locator('#confirm-dialog button[value=confirm]').click();
  await page.waitForFunction(() => !document.querySelector('#detect').disabled && document.querySelector('#grid-edits').textContent.includes('自动补线 1 条'));
  assert.ok((await page.locator('#grid-edits').textContent()).includes('合并窄格 1 处'));
  assert.equal(await page.locator('#cols').inputValue(), '12'); assert.equal(await page.locator('#rows').inputValue(), '6');
  assert.equal(await page.locator('#grid-issue-count').textContent(), '没有宽窄异常');
  await page.locator('#undo').click();
  assert.equal(await page.locator('#grid-issue-count').textContent(), '2 处过宽 · 1 处过窄');
  await page.locator('#redo').click();
  assert.equal(await page.locator('#grid-issue-count').textContent(), '没有宽窄异常');
  await page.screenshot({ path: path.join(dir, 'grid-tuning.png'), fullPage: true });
  await page.goto(pathToFileURL(path.resolve(__dirname, '../index.html')).href);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(250);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: path.join(dir, 'mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 768, height: 1024 }); await page.waitForTimeout(250);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: path.join(dir, 'tablet.png'), fullPage: true });
  assert.deepEqual(errors, []); console.log('Browser checks passed: canvas, selection, grid drag, local sampling, undo/redo, project and tuning round-trip, anomaly navigation, automatic insertion/merge, PNG dimensions, transparency, mobile and tablet.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
